spring:
  datasource:
    dynamic:
      hikari:
        connection-test-query: select 1
        idle-timeout: 10000
        max-pool-size: 20
        min-idle: 10
        connection-timeout: 30000
      strict: false
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://xxx:3306/${spring.application.name}?autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
          username: xxx
          password: xxx
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://xxx:3306/${spring.application.name}?autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
          username: xxx
          password: xxx
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host-name: xxx
    database: 7
    port: 6379
    timeout: 5000 #连接超时时间
    password: xxx
    pool:
      maxTotal: -1 # 连接池最大连接数（使用负值表示没有限制）
      maxWaitMillis: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #    host-name: 183.134.61.151
    jedis:
      pool:
        max-idle: 20
        min-idle: 1
  scheduling:
    enable: true

logging:
  config: classpath:log/logback-boot.xml
  file:
    path: /www/metaai/logs
    name: ${spring.application.name}
  level:
    com.shitouren.core: info

meta:
  pi:
    server-access-key: ''

pay:
  channel:
    domain:
    address-url: ${pay.channel.domain}/address?amount=
    create-url: ${pay.channel.domain}/created?search_db=history
    query-url: ${pay.channel.domain}/query?search_db=history&query_key=id&query_type=equal&query_value=
